import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from '../components';

const RenderCards = ({ data, title}) => {
  if(data?.length > 0){
    return data.map((post) => <Card key={post._id}{...post}/>)
  }

  else return(
    <h2 className='mt-5 font-bold text-purple-800 text-xl uppercase'>{title}</h2>
  )
}

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setallPosts] = useState(null);

  const [searchText, setSearchText] = useState('')

  return (
    <div className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-black text-[32px] font-mono'>The Community</h1>
        <p className='mt-2 text-gray-600 text-[20px] max-w-[70vw]'>
          Browse through a collection of imaginative and visually stunning images generated by AI.
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-gray-800 text-xl mb-3'>
                Showing results for <span className='text-black'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
               {searchText ? (
                <RenderCards 
                  data=""
                  title="No search results found"
                />
               ) : (
                <RenderCards 
                  data =""
                  title = "No posts found"
                />
               )}
            </div>
          </>
        )}
      </div>
    </div>
  )
}

export default Home