import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from '../components';

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setallPosts] = useState(null);

  return (
    <div className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-black text-[32px] font-mono'>The Community</h1>
        <p className='mt-2 text-gray-600 text-[20px] max-w-[70vw]'>
          Browse through a collection of imaginative and visually stunning images generated by AI.
        </p>
      </div>
    </div>
  )
}

export default Home